### ISSUE TITLE
Incorrect testcase filter with certain projects

### ISSUE THREAD

**Issue by X9VoiD** [Issafalcon/neotest-dotnet#22]
### Reproduction

```
dotnet new xunit -n NormalProject
dotnet new xunit -n Problematic.Project
dotnet restore NormalProject
dotnet restore Problematic.Project
```

Hover cursor over NormalProject.UnitTest1.Test1, then invoke `require("neotest").run.run()` (via binding or `:lua`).

Observe that it ran without issues (except for the already known test failure false-positive).

Hover cursor over Problematic.Project.UnitTest1.Test1, then invoke `require("neotest").run.run()`

### Expected behavior

Should work just fine.

### Actual behavior

Test fails to run with
```
No test matches the given testcase filter `FullyQualifiedName~Problematic.Namespace.Test1`
```

---

It seems that neotest-dotnet fails to generate the correct filter **when the root namespace/project has a dot in it.** The filter should be `FullyQualifiedName~Problematic.Namespace.UnitTest1.Test1`

**Comment by Issafalcon** [comment]
Hi @X9VoiD . Thanks for raising an issue!

I followed the steps in your reproduction description and did find the same outcome, that fully qualified filter was incorrect, but I had a slightly different reason for it. The FQN message I get is `No test matches the given testcase filter `FullyQualifiedName~Problematic.Project.Test1` which shows that the namespace portion (`UnitTest1` by default when created using the .NET 6.0 SDK CLI). The reason for this is because I was relying on the `using Xunit` statement to be somewhere in the file, whereas creating a project using the above method, puts the global using in a separate file, so it never picks up the namespace (and thus doesn't add it to the FQN when forming the filter).

I will fix this issue, but it would be good if you can confirm if what you see is the same thing? 

If it is different, could you confirm what SDK you are using for .NET to create the projects. Also, I'm not entirely sure what you mean by "Observe that it ran without issues (except for the already known test failure false-positive)." What is the already know test failure false-positive you refer to?

**Comment by X9VoiD** [comment]
> What is the already know test failure false-positive you refer to?

The README.md states "the result output is currently not correctly relayed back to neotest". So I assumed this failure (see pic below) is just a false positive, though it is weird that it also happens even without `{ strategy = dap }`. Is this a new thing?

![image](https://user-images.githubusercontent.com/10338031/201489396-bfd45226-72cd-4e41-b300-116209dae444.png)

###### Note that the test passed but neotest-dotnet says it failed

> I will fix this issue, but it would be good if you can confirm if what you see is the same thing?

Yeah, seems like adding `using Xunit;` on the file fixed the error.

![image](https://user-images.githubusercontent.com/10338031/201489561-41281434-a9a7-4607-be3d-b0f74c81f999.png)

**Comment by Issafalcon** [comment]
Thanks @X9VoiD - Interesting about the mismatch between the test output and the display. It shouldn't be misbehaving like that outside of the debug strategy.

I've pushed a fix for the issue when the using statement are missing. Could you give it another go and see if evertyhing seems OK now? 

If you still see the mismatched output and symbols against the tests, could you please open another issue and stick in the output from your trx files? I notice you are using .NET 7.0, so I'm wondering if they might have changed the trx output in any way. The outcomes for neotest-dotnet tests (and thus the symbols) depend on parsing the trx files, so if one of the xml attributes is unexpected, it will report it as a failure if it cannot parse the output file.

**Comment by X9VoiD** [comment]
Can confirm it's working now, thanks!

Will be opening up new issues for the other stuff that I found.
