### ISSUE TITLE
Test Not Found

### ISSUE THREAD

**Issue by MrFisher404** [Issafalcon/neotest-dotnet#5]
Hi and first of all thank you for working on this project!

I can't wait until it is completely finished. 

I integrated your plugin in my neotest but always encounter the same problem, that it doesn't find my tests. When I use vim-test everything works. 
Since I am not really fluid in lua or treesitter queries, I can't be of a big help in this project. But I saw that you changed in you last commit to treesitter and in the query you check for [TestMethod] and [TestClass].
We use the Nunit.Framework and the Tags in our Tests are [TestFixure] and [Test]. Maybe this could be a reason?
As I said I couldn't go through all the code and this is just a wild guess. But maybe you could Check if it is working for you with the Nunit.Framework Nuget?

Thank you again and can't wait to use this in my workflow!

**Comment by Issafalcon** [comment]
Hey there @MrFisher404 ! Thanks for checking out the adapter. It is very much early days yet for sure, so you might need to bear with me. I did switch to using treesitter because I was having some real issues with getting specflow tests to reliably show up using omnisharp LSP. However, it now means it's a bit of 'back to square one' until I can write all the necessary treesitter queries to cover off the test frameworks.

For now, once I have it in a state where it at least matches the functionality provided by the vim-test adapter, I'll announce that it's ready to use. Aiming to support all the main test runners (Xunit, Nunit, Mstest plus the specflow variants)

**Comment by Issafalcon** [comment]
@MrFisher404 - Try it now. You should see your Nunit tests appearing
